/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BookIs.view;

/**
 *
 * @author ajita
 */
public class AboutUsPage extends javax.swing.JFrame {

    /**
     * Creates new form AboutUsPage
     */
    public AboutUsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblAboutusHeading = new javax.swing.JLabel();
        lblOurmissionHeading = new javax.swing.JLabel();
        lblBelowAboutus = new javax.swing.JLabel();
        lblOurmissionbody1 = new javax.swing.JLabel();
        lblOurmissionbody2 = new javax.swing.JLabel();
        lblOurmissionbody3 = new javax.swing.JLabel();
        lblOurmissionbody4 = new javax.swing.JLabel();
        lbOurstoryHeading = new javax.swing.JLabel();
        lblOurstoryBody1 = new javax.swing.JLabel();
        lblOurstoryBody2 = new javax.swing.JLabel();
        lblOurstoryBody3 = new javax.swing.JLabel();
        lblOurstoryBody4 = new javax.swing.JLabel();
        lblBookIcon = new javax.swing.JLabel();
        lblBooksold = new javax.swing.JLabel();
        lblCustomerIcon = new javax.swing.JLabel();
        lblCustomerNumber = new javax.swing.JLabel();
        lblWorkforceIcon = new javax.swing.JLabel();
        lblWorkforceNumber = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainScreen.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblLogo.setText("kafkaklub");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/AboutUsImg (2).jpg"))); // NOI18N
        lblImage.setText("jLabel2");

        lblAboutusHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAboutusHeading.setText("ABOUT US");

        lblOurmissionHeading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOurmissionHeading.setText("Our Mission");

        lblBelowAboutus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBelowAboutus.setText("Kafkaklub is your go to place if you are a book connoisseur.  ");

        lblOurmissionbody1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurmissionbody1.setText("At KafkaKlub, our mission is to make book easily accessible for everyone who has a penchant for reading.");

        lblOurmissionbody2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurmissionbody2.setText("We believe that books can bring positive change. Our goal is to create a diverse collection of books form");

        lblOurmissionbody3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurmissionbody3.setText("cult classics to the popular ones of recent times. We are devoted in providing an absolutely best shopping");

        lblOurmissionbody4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurmissionbody4.setText("experience for our consumers.");

        lbOurstoryHeading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbOurstoryHeading.setText("Our Story");

        lblOurstoryBody1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurstoryBody1.setText("While studying in a college named Micheal Scott Institute Of Technology, two best friends Ted and Marshall,");

        lblOurstoryBody2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurstoryBody2.setText("who were bibliophile, thought going to a physical book store is a hassle, so they decided on creating an ");

        lblOurstoryBody3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurstoryBody3.setText("e-book store. The e-book store was founded by them in 2007 and they named the e-book store KafkaKlub ");

        lblOurstoryBody4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOurstoryBody4.setText("after their one of the favorite authors Franz Kafka.");

        lblBookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/BookSoldIcon.jpg"))); // NOI18N
        lblBookIcon.setText("jLabel16");

        lblBooksold.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBooksold.setText("30,000+ books sold ");

        lblCustomerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/ConsumerIcon.jpg"))); // NOI18N
        lblCustomerIcon.setText("jLabel17");

        lblCustomerNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerNumber.setText("8000+ customers");

        lblWorkforceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/EmployeeIcon.jpg"))); // NOI18N
        lblWorkforceIcon.setText("jLabel19");

        lblWorkforceNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWorkforceNumber.setText("200+ workforce");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addComponent(lblAboutusHeading)
                                .addGap(321, 321, 321)
                                .addComponent(lblLogo))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblOurmissionbody1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurmissionbody2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurmissionbody3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurmissionHeading)
                                        .addComponent(lbOurstoryHeading)
                                        .addComponent(lblOurstoryBody1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurstoryBody2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurstoryBody3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOurstoryBody4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblOurmissionbody4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                        .addComponent(lblBooksold)
                                        .addGap(94, 94, 94)
                                        .addComponent(lblCustomerNumber)
                                        .addGap(93, 93, 93)
                                        .addComponent(lblWorkforceNumber))))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(lblBelowAboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(lblBookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(lblCustomerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(lblWorkforceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addComponent(lblAboutusHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBelowAboutus)
                .addGap(15, 15, 15)
                .addComponent(lblOurmissionHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOurmissionbody1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurmissionbody2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurmissionbody3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurmissionbody4)
                .addGap(26, 26, 26)
                .addComponent(lbOurstoryHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOurstoryBody1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurstoryBody2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurstoryBody3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOurstoryBody4)
                .addGap(83, 83, 83)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkforceIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkforceNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBooksold, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCustomerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         new HomePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lbOurstoryHeading;
    private javax.swing.JLabel lblAboutusHeading;
    private javax.swing.JLabel lblBelowAboutus;
    private javax.swing.JLabel lblBookIcon;
    private javax.swing.JLabel lblBooksold;
    private javax.swing.JLabel lblCustomerIcon;
    private javax.swing.JLabel lblCustomerNumber;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOurmissionHeading;
    private javax.swing.JLabel lblOurmissionbody1;
    private javax.swing.JLabel lblOurmissionbody2;
    private javax.swing.JLabel lblOurmissionbody3;
    private javax.swing.JLabel lblOurmissionbody4;
    private javax.swing.JLabel lblOurstoryBody1;
    private javax.swing.JLabel lblOurstoryBody2;
    private javax.swing.JLabel lblOurstoryBody3;
    private javax.swing.JLabel lblOurstoryBody4;
    private javax.swing.JLabel lblWorkforceIcon;
    private javax.swing.JLabel lblWorkforceNumber;
    private javax.swing.JPanel pnlMainScreen;
    // End of variables declaration//GEN-END:variables
}
