/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BookIs.view;

/**
 *
 * @author ajita
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    public ContactUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblContactform = new javax.swing.JLabel();
        txtfldEmail = new javax.swing.JTextField();
        txtfldPhone = new javax.swing.JTextField();
        txtfldFullName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblFollowusat = new javax.swing.JLabel();
        lblThankyouforvisiting = new javax.swing.JLabel();
        lblLocationIcon = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblContactnumber = new javax.swing.JLabel();
        lblPhoneIcon = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblContactAddress = new javax.swing.JLabel();
        lblEmailIcon = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblConactusat = new javax.swing.JLabel();
        lblFacebookIcon = new javax.swing.JLabel();
        lblInstagram = new javax.swing.JLabel();
        btnbackhome = new javax.swing.JButton();
        lblEmailfortxtfld = new javax.swing.JLabel();
        lblFullNamefortxtfld = new javax.swing.JLabel();
        lblPhonefortxtfld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainScreen.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblLogo.setText("kafkaklub");

        lblContactform.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContactform.setText("Contact Form");

        txtfldEmail.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtfldEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtfldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldEmailActionPerformed(evt);
            }
        });

        txtfldPhone.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtfldPhone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtfldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPhoneActionPerformed(evt);
            }
        });

        txtfldFullName.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtfldFullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtfldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldFullNameActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblFollowusat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFollowusat.setText("Follow Us At:");

        lblThankyouforvisiting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThankyouforvisiting.setText("Thank you for visiting us!!!");

        lblLocationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/LocationIcon.jpg"))); // NOI18N

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        lblContactnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactnumber.setText("+977 9847632018");

        lblPhoneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/PhoneIcon.jpg"))); // NOI18N
        lblPhoneIcon.setText("jLabel8");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setText("Phone");

        lblContactAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactAddress.setText("Surunga, Jhapa,Nepal");

        lblEmailIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/EmailIcon.jpg"))); // NOI18N
        lblEmailIcon.setText("Email");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmailAddress.setText("kafkaclub@gmail.com");

        lblConactusat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConactusat.setText("Contact Us At:");

        lblFacebookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/FacebookIcon.jpg"))); // NOI18N
        lblFacebookIcon.setText("jLabel16");

        lblInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/InstagramIcon.jpg"))); // NOI18N
        lblInstagram.setText("jLabel17");

        btnbackhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbackhome.setText("BACK");
        btnbackhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackhomeActionPerformed(evt);
            }
        });

        lblEmailfortxtfld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailfortxtfld.setText("Email:");

        lblFullNamefortxtfld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFullNamefortxtfld.setText("Full Name:");

        lblPhonefortxtfld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhonefortxtfld.setText("Phone:");

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhoneIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLocationIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactnumber)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmailAddress)
                                            .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblContactAddress))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblFullNamefortxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmailfortxtfld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhonefortxtfld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfldPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(txtfldEmail)))))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(559, 559, 559)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addComponent(lblFollowusat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                                .addComponent(lblContactform)
                                .addGap(180, 180, 180))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addComponent(lblInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblFacebookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnbackhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLogo))
                        .addGap(447, 447, 447)
                        .addComponent(lblThankyouforvisiting)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainScreenLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(lblConactusat)
                    .addContainerGap(1128, Short.MAX_VALUE)))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblContactform, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo)
                        .addGap(47, 47, 47)
                        .addComponent(lblFollowusat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocationIcon)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblContactAddress))
                            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFacebookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPhoneIcon)
                        .addGap(42, 42, 42))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFullNamefortxtfld))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLocation)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblPhone))
                            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmailfortxtfld)))
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhonefortxtfld)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblContactnumber)
                                .addGap(27, 27, 27)))
                        .addGap(16, 16, 16)))
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmailIcon)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailAddress)))
                .addGap(15, 15, 15)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblThankyouforvisiting, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnbackhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainScreenLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(lblConactusat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtfldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldFullNameActionPerformed

    private void txtfldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPhoneActionPerformed

    private void txtfldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldEmailActionPerformed

    private void btnbackhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackhomeActionPerformed
         new HomePage().setVisible(true);
    }//GEN-LAST:event_btnbackhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create abtnbackhomeconorm */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnbackhome;
    private javax.swing.JLabel lblConactusat;
    private javax.swing.JLabel lblContactAddress;
    private javax.swing.JLabel lblContactform;
    private javax.swing.JLabel lblContactnumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailIcon;
    private javax.swing.JLabel lblEmailfortxtfld;
    private javax.swing.JLabel lblFacebookIcon;
    private javax.swing.JLabel lblFollowusat;
    private javax.swing.JLabel lblFullNamefortxtfld;
    private javax.swing.JLabel lblInstagram;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationIcon;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneIcon;
    private javax.swing.JLabel lblPhonefortxtfld;
    private javax.swing.JLabel lblThankyouforvisiting;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JTextField txtfldEmail;
    private javax.swing.JTextField txtfldFullName;
    private javax.swing.JTextField txtfldPhone;
    // End of variables declaration//GEN-END:variables
}
