/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BookIs.view;

/**
 *
 * @author ajita
 */
public class ExplorePage extends javax.swing.JFrame {

    /**
     * Creates new form ExplorePage
     */
    public ExplorePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblOurcollection = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();
        lblImage6 = new javax.swing.JLabel();
        lblRs1800 = new javax.swing.JLabel();
        lblBypattismith = new javax.swing.JLabel();
        lblByfranzkafka = new javax.swing.JLabel();
        lblByfranzkafka2 = new javax.swing.JLabel();
        lblJustkids = new javax.swing.JLabel();
        lblRs2400 = new javax.swing.JLabel();
        lblLetterstomilena = new javax.swing.JLabel();
        lblMetamorphosis = new javax.swing.JLabel();
        lblRs2000 = new javax.swing.JLabel();
        lblByhanyayanagihara = new javax.swing.JLabel();
        lblBycaseymcquiston = new javax.swing.JLabel();
        lblRs1000 = new javax.swing.JLabel();
        lblAlittlelife = new javax.swing.JLabel();
        lblThehousemaid = new javax.swing.JLabel();
        lblRs800 = new javax.swing.JLabel();
        lblByfreidamcfadden = new javax.swing.JLabel();
        lblRedwhiteandroyalblue = new javax.swing.JLabel();
        lblRs700 = new javax.swing.JLabel();
        btnAddtocart1 = new javax.swing.JButton();
        btnAddtocart2 = new javax.swing.JButton();
        btnAddtocart3 = new javax.swing.JButton();
        btnAddtocart4 = new javax.swing.JButton();
        btnAddtocart5 = new javax.swing.JButton();
        btnAddtocart6 = new javax.swing.JButton();
        btnbackhomeexp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainScreen.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblLogo.setText("kafkaklub");

        lblOurcollection.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOurcollection.setForeground(new java.awt.Color(153, 0, 0));
        lblOurcollection.setText("Our Collection");

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/JKimg.jpg"))); // NOI18N
        lblImage1.setText("jLabel3");

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/LTMimg.jpg"))); // NOI18N
        lblImage2.setText("jLabel4");

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/MMimg.jpg"))); // NOI18N
        lblImage3.setText("jLabel5");

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/RWRBimg.jpg"))); // NOI18N
        lblImage4.setText("jLabel6");

        lblImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/TLLimg.jpg"))); // NOI18N
        lblImage5.setText("jLabel7");

        lblImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BookIs/resources/THMimg.jpg"))); // NOI18N
        lblImage6.setText("jLabel8");

        lblRs1800.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs1800.setForeground(new java.awt.Color(153, 0, 0));
        lblRs1800.setText(" Rs 1800");

        lblBypattismith.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBypattismith.setForeground(new java.awt.Color(153, 0, 0));
        lblBypattismith.setText("by Patti Smith");

        lblByfranzkafka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblByfranzkafka.setForeground(new java.awt.Color(153, 0, 0));
        lblByfranzkafka.setText("by Franz Kafka");

        lblByfranzkafka2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblByfranzkafka2.setForeground(new java.awt.Color(153, 0, 0));
        lblByfranzkafka2.setText("by Franz Kafka");

        lblJustkids.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJustkids.setForeground(new java.awt.Color(153, 0, 0));
        lblJustkids.setText("Just Kids");

        lblRs2400.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs2400.setForeground(new java.awt.Color(153, 0, 0));
        lblRs2400.setText(" Rs 2400");

        lblLetterstomilena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLetterstomilena.setForeground(new java.awt.Color(153, 0, 0));
        lblLetterstomilena.setText("Letters to Milena");

        lblMetamorphosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMetamorphosis.setForeground(new java.awt.Color(153, 0, 0));
        lblMetamorphosis.setText("Metamorphosis");

        lblRs2000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs2000.setForeground(new java.awt.Color(153, 0, 0));
        lblRs2000.setText("Rs 2000");

        lblByhanyayanagihara.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblByhanyayanagihara.setForeground(new java.awt.Color(153, 0, 0));
        lblByhanyayanagihara.setText("by Hanya Yanagihara");

        lblBycaseymcquiston.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBycaseymcquiston.setForeground(new java.awt.Color(153, 0, 0));
        lblBycaseymcquiston.setText("by Casey McQuiston");

        lblRs1000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs1000.setForeground(new java.awt.Color(153, 0, 0));
        lblRs1000.setText("Rs 1000");

        lblAlittlelife.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAlittlelife.setForeground(new java.awt.Color(153, 0, 0));
        lblAlittlelife.setText("A Little Life ");

        lblThehousemaid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblThehousemaid.setForeground(new java.awt.Color(153, 0, 0));
        lblThehousemaid.setText("The HouseMaid");

        lblRs800.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs800.setForeground(new java.awt.Color(153, 0, 0));
        lblRs800.setText("Rs 800");

        lblByfreidamcfadden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblByfreidamcfadden.setForeground(new java.awt.Color(153, 0, 0));
        lblByfreidamcfadden.setText("by Freida McFadden");

        lblRedwhiteandroyalblue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRedwhiteandroyalblue.setForeground(new java.awt.Color(153, 0, 0));
        lblRedwhiteandroyalblue.setText("Red White & Royal blue");

        lblRs700.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRs700.setForeground(new java.awt.Color(153, 0, 0));
        lblRs700.setText("Rs 700");

        btnAddtocart1.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart1.setText("Add To Cart");
        btnAddtocart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart1ActionPerformed(evt);
            }
        });

        btnAddtocart2.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart2.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart2.setText("Add To Cart");
        btnAddtocart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart2ActionPerformed(evt);
            }
        });

        btnAddtocart3.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart3.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart3.setText("Add To Cart");
        btnAddtocart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart3ActionPerformed(evt);
            }
        });

        btnAddtocart4.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart4.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart4.setText("Add To Cart");
        btnAddtocart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart4ActionPerformed(evt);
            }
        });

        btnAddtocart5.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart5.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart5.setText("Add To Cart");
        btnAddtocart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart5ActionPerformed(evt);
            }
        });

        btnAddtocart6.setBackground(new java.awt.Color(153, 0, 0));
        btnAddtocart6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddtocart6.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart6.setText("Add To Cart");
        btnAddtocart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocart6ActionPerformed(evt);
            }
        });

        btnbackhomeexp.setBackground(new java.awt.Color(153, 0, 0));
        btnbackhomeexp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbackhomeexp.setForeground(new java.awt.Color(255, 255, 255));
        btnbackhomeexp.setText("BACK");
        btnbackhomeexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackhomeexpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJustkids)
                    .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBypattismith)
                    .addComponent(lblRs1800)
                    .addComponent(btnAddtocart1))
                .addGap(62, 62, 62)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLetterstomilena)
                    .addComponent(lblByfranzkafka2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRs2400)
                    .addComponent(btnAddtocart6)
                    .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetamorphosis)
                    .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblByfranzkafka)
                    .addComponent(lblRs2000)
                    .addComponent(btnAddtocart2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addComponent(lblImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addComponent(lblByhanyayanagihara)
                            .addComponent(lblRs1000)
                            .addComponent(btnAddtocart3))
                        .addGap(12, 12, 12)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRedwhiteandroyalblue)
                            .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBycaseymcquiston)
                            .addComponent(lblRs700)
                            .addComponent(btnAddtocart4)))
                    .addComponent(lblAlittlelife))
                .addGap(36, 36, 36)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThehousemaid)
                    .addComponent(lblByfreidamcfadden)
                    .addComponent(lblRs800)
                    .addComponent(btnAddtocart5))
                .addGap(38, 38, 38))
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(470, 470, 470)
                        .addComponent(lblOurcollection))
                    .addComponent(btnbackhomeexp))
                .addGap(0, 673, Short.MAX_VALUE))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOurcollection, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addComponent(lblImage6)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addComponent(lblAlittlelife, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblByhanyayanagihara, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBycaseymcquiston, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRs1000)
                            .addComponent(lblRs700)))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblImage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJustkids, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBypattismith, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImage2)
                            .addComponent(lblImage3)
                            .addComponent(lblImage5)
                            .addComponent(lblImage4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRedwhiteandroyalblue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblThehousemaid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblByfreidamcfadden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLetterstomilena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMetamorphosis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblByfranzkafka2)
                                    .addComponent(lblByfranzkafka))
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblRs2400, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblRs2000)))
                                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(lblRs800, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35)
                                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnAddtocart6)
                                            .addComponent(btnAddtocart1)
                                            .addComponent(btnAddtocart2)
                                            .addComponent(btnAddtocart3)
                                            .addComponent(btnAddtocart4)
                                            .addComponent(btnAddtocart5)))
                                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(lblRs1800, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnbackhomeexp))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtocart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart1ActionPerformed

    private void btnAddtocart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart2ActionPerformed

    private void btnAddtocart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart3ActionPerformed

    private void btnAddtocart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart4ActionPerformed

    private void btnAddtocart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart5ActionPerformed

    private void btnAddtocart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocart6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtocart6ActionPerformed

    private void btnbackhomeexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackhomeexpActionPerformed
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnbackhomeexpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExplorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExplorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExplorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExplorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExplorePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtocart1;
    private javax.swing.JButton btnAddtocart2;
    private javax.swing.JButton btnAddtocart3;
    private javax.swing.JButton btnAddtocart4;
    private javax.swing.JButton btnAddtocart5;
    private javax.swing.JButton btnAddtocart6;
    private javax.swing.JButton btnbackhomeexp;
    private javax.swing.JLabel lblAlittlelife;
    private javax.swing.JLabel lblBycaseymcquiston;
    private javax.swing.JLabel lblByfranzkafka;
    private javax.swing.JLabel lblByfranzkafka2;
    private javax.swing.JLabel lblByfreidamcfadden;
    private javax.swing.JLabel lblByhanyayanagihara;
    private javax.swing.JLabel lblBypattismith;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblImage6;
    private javax.swing.JLabel lblJustkids;
    private javax.swing.JLabel lblLetterstomilena;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMetamorphosis;
    private javax.swing.JLabel lblOurcollection;
    private javax.swing.JLabel lblRedwhiteandroyalblue;
    private javax.swing.JLabel lblRs1000;
    private javax.swing.JLabel lblRs1800;
    private javax.swing.JLabel lblRs2000;
    private javax.swing.JLabel lblRs2400;
    private javax.swing.JLabel lblRs700;
    private javax.swing.JLabel lblRs800;
    private javax.swing.JLabel lblThehousemaid;
    private javax.swing.JPanel pnlMainScreen;
    // End of variables declaration//GEN-END:variables
}
