/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BookIs.view;

/**
 *
 * @author ajita
 */
public class HomePage extends javax.swing.JFrame {



    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblOurbestsellers = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnaboutus = new javax.swing.JButton();
        btnexplore = new javax.swing.JButton();
        btninformation = new javax.swing.JButton();
        btncontact = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainScreen.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblLogo.setText("kafkaklub");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/HomeImg.jpg"))); // NOI18N
        lblImage.setText("jLabel2");

        lblHeading.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(153, 0, 51));
        lblHeading.setText("Feast your eyes on a good book!!");

        lblOurbestsellers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOurbestsellers.setForeground(new java.awt.Color(153, 0, 0));
        lblOurbestsellers.setText("Our Bestsellers");

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/GreenlightImg.jpg"))); // NOI18N
        lblImage1.setText("jLabel5");

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/AtomicHabitImg.jpg"))); // NOI18N
        lblImage2.setText("jLabel6");

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/TheSilentPatient.jpg"))); // NOI18N
        lblImage3.setText("jLabel7");

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/AmancalledoveImg.jpg"))); // NOI18N
        lblImage4.setText("jLabel8");

        lblImage5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImage5.setForeground(new java.awt.Color(153, 0, 0));
        lblImage5.setText("Trending This Week");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/SHOEHimg.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/TMIYimg.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/TKRimg.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookis/resources/TBJimg.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");

        btnaboutus.setBackground(new java.awt.Color(153, 0, 0));
        btnaboutus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnaboutus.setForeground(new java.awt.Color(255, 255, 255));
        btnaboutus.setText("ABOUT US");
        btnaboutus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });

        btnexplore.setBackground(new java.awt.Color(153, 0, 0));
        btnexplore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexplore.setForeground(new java.awt.Color(255, 255, 255));
        btnexplore.setText("EXPLORE");
        btnexplore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnexplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexploreActionPerformed(evt);
            }
        });

        btninformation.setBackground(new java.awt.Color(153, 0, 0));
        btninformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btninformation.setForeground(new java.awt.Color(255, 255, 255));
        btninformation.setText("INFORMATION");
        btninformation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btninformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformationActionPerformed(evt);
            }
        });

        btncontact.setBackground(new java.awt.Color(153, 0, 0));
        btncontact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncontact.setForeground(new java.awt.Color(255, 255, 255));
        btncontact.setText("CONTACT US");
        btncontact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontactActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(153, 0, 0));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("LOG OUT");
        btnlogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnaboutus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnexplore)
                                .addGap(12, 12, 12)
                                .addComponent(btninformation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncontact)
                                .addGap(122, 122, 122))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblHeading))
                                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(0, 32, Short.MAX_VALUE)))
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(lblOurbestsellers))
                            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(lblImage5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogo)
                            .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnaboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnexplore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btninformation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncontact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(lblHeading)
                        .addGap(27, 27, 27)
                        .addComponent(lblOurbestsellers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImage3)
                            .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImage4)
                            .addComponent(lblImage2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))))
                .addContainerGap(1339, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        new AboutUsPage().setVisible(true);
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btninformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformationActionPerformed
        new InformationPage().setVisible(true);
    }//GEN-LAST:event_btninformationActionPerformed

    private void btnexploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexploreActionPerformed
        new ExplorePage().setVisible(true);
    }//GEN-LAST:event_btnexploreActionPerformed

    private void btncontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontactActionPerformed
       new ContactUs().setVisible(true);
    }//GEN-LAST:event_btncontactActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // Show a confirmation dialog
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Are you sure that you want to exit this page?", 
        "Logout Confirmation", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    // If YES is clicked
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // Close the current window and show the HomePage
        this.setVisible(false); // Hide the current window
        
    }
        
    }//GEN-LAST:event_btnlogoutActionPerformed
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btncontact;
    private javax.swing.JButton btnexplore;
    private javax.swing.JButton btninformation;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOurbestsellers;
    private javax.swing.JPanel pnlMainScreen;
    // End of variables declaration//GEN-END:variables
}
